/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComoTrabajamosRouteImport } from './routes/como-trabajamos'
import { Route as SectoresRouteImport } from './routes/sectores'
import { Route as SolucionesRouteImport } from './routes/soluciones'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoTrabajamosRoute = ComoTrabajamosRouteImport.update({
  id: '/como-trabajamos',
  path: '/como-trabajamos',
  getParentRoute: () => rootRouteImport,
} as any)
const SectoresRoute = SectoresRouteImport.update({
  id: '/sectores',
  path: '/sectores',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucionesRoute = SolucionesRouteImport.update({
  id: '/soluciones',
  path: '/soluciones',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/como-trabajamos': typeof ComoTrabajamosRoute
  '/sectores': typeof SectoresRoute
  '/soluciones': typeof SolucionesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/como-trabajamos': typeof ComoTrabajamosRoute
  '/sectores': typeof SectoresRoute
  '/soluciones': typeof SolucionesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/como-trabajamos': typeof ComoTrabajamosRoute
  '/sectores': typeof SectoresRoute
  '/soluciones': typeof SolucionesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/como-trabajamos' | '/sectores' | '/soluciones'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/como-trabajamos' | '/sectores' | '/soluciones'
  id: '__root__' | '/' | '/como-trabajamos' | '/sectores' | '/soluciones'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComoTrabajamosRoute: typeof ComoTrabajamosRoute
  SectoresRoute: typeof SectoresRoute
  SolucionesRoute: typeof SolucionesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-trabajamos': {
      id: '/como-trabajamos'
      path: '/como-trabajamos'
      fullPath: '/como-trabajamos'
      preLoaderRoute: typeof ComoTrabajamosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sectores': {
      id: '/sectores'
      path: '/sectores'
      fullPath: '/sectores'
      preLoaderRoute: typeof SectoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soluciones': {
      id: '/soluciones'
      path: '/soluciones'
      fullPath: '/soluciones'
      preLoaderRoute: typeof SolucionesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComoTrabajamosRoute: ComoTrabajamosRoute,
  SectoresRoute: SectoresRoute,
  SolucionesRoute: SolucionesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
